### ISSUE TITLE
Some dependencies (at least Folly) are broken on the newest branch. Does anyone have a variant of install_all.sh that works on kaixhin/cuda-torch Ubuntu 14.04 with fixed stable versions? Setting current=0 does not work.

### ISSUE THREAD

**Issue by lukebrandl** [bgshih/crnn#129]
I've been in dependency hell the last few hours trying to get crnn dependencies set up. Even docker which is supposed to be around to help me avoid this issue has broken versions. 

I'm trying to build crnn on 16.04 (with the docker image being kaixhin/cuda-torch 14.04) with CUDA 7.5 using the suggested docker build. I've been running into all kinds of build issues. Rather than trying to find some combination of versions that works I was wondering if anyone with a working docker build could share the versions they are using in install_all.sh. I think the install_all.sh current=0 version should work, but it runs into some version looking issues 

`/tmp/fblualib-build.wcVcVm/thpp/thpp/../thpp/detail/TensorGeneric.h:201:37: error: return-statement with a value, in function returning 'void' [-fpermissive]
     return THTensor_(prod)(r, t, dim);
`
That I'd rather find a way around. Isn't the whole point of docker to have at least the option of fixing versions to guarantee a successful build?
