### ISSUE TITLE
unable to compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by saxenarohit** [bgshih/crnn#113]
`[ 25%] Building CXX object CMakeFiles/crnn.dir/ctc.cpp.o
In file included from /home/user/torch/install/include/thpp/Tensor.h:14:0,
                 from /media/u556552/f5c1b8df-0e60-4c24-ad5f-2868c5732ecc/Advertisements/text-reco/TextBoxes_plusplus/crnn/src/cpp/ctc.cpp:8:
/home/u556552/torch/install/include/thpp/Storage.h:22:43: fatal error: thpp/if/gen-cpp2/Tensor_types.h: No such file or directory
compilation terminated.
CMakeFiles/crnn.dir/build.make:86: recipe for target 'CMakeFiles/crnn.dir/ctc.cpp.o' failed
make[2]: *** [CMakeFiles/crnn.dir/ctc.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/crnn.dir/all' failed
make[1]: *** [CMakeFiles/crnn.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
cp: cannot stat '*.so': No such file or directory
`
